# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-22 03:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photogallery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments_text', models.TextField()),
            ],
            options={
                'db_table': 'comments',
            },
        ),
        migrations.RemoveField(
            model_name='picture',
            name='pic_likes',
        ),
        migrations.AlterField(
            model_name='picture',
            name='pic_date',
            field=models.DateTimeField(verbose_name='Datetime'),
        ),
        migrations.AlterField(
            model_name='picture',
            name='pic_image',
            field=models.ImageField(upload_to='static/gallery/', verbose_name='Select Image'),
        ),
        migrations.AlterField(
            model_name='picture',
            name='pic_text',
            field=models.TextField(verbose_name='Annotation'),
        ),
        migrations.AlterField(
            model_name='picture',
            name='pic_title',
            field=models.CharField(max_length=200, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='comments',
            name='comments_article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photogallery.picture'),
        ),
    ]
