# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-22 05:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photogallery', '0003_auto_20170122_0546'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='comment',
            table='comment',
        ),
    ]
