# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-22 10:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('photogallery', '0004_auto_20170122_0550'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 22, 10, 28, 9, 382872, tzinfo=utc)),
        ),
    ]
