# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-22 12:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('photogallery', '0005_comment_comment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 22, 12, 4, 3, 179177, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_text',
            field=models.TextField(verbose_name='Comment Text'),
        ),
    ]
