# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-22 12:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('photogallery', '0006_auto_20170122_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 22, 12, 17, 41, 658412, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_pic',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='photogallery.picture'),
        ),
    ]
