# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-21 21:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photogallery', '0011_auto_20170722_0018'),
    ]

    operations = [
        migrations.RenameField(
            model_name='picture',
            old_name='pic_views',
            new_name='views',
        ),
    ]
